incremental udpate

diff --git a/image_build b/image_build
--- a/image_build
+++ b/image_build
@@ -1,6 +1,6 @@
 #!/bin/bash
 # base script
-set -xeuo pipefail
+set -euo pipefail
 
 ARCH="$(uname -m)"
 MANIFEST=0
@@ -8,17 +8,22 @@ TYPE=''
 
 OPTIND=1
 
-get_arch_repo_name() {
+
+#
+# Provide arch names for registory path
+#
+# used to create arch specific tag path
+get_registry_arch() {
     local -r arch="${1}"
     case "${arch}" in
+        i386|amd64|arm64v8|ppc64le|s390x)
+            echo "${arch}";;
         x86_64)
             echo 'amd64';;
-        aarch64)
+        aarch64|arm64|arm64/v8)
             echo 'arm64v8';;
-        ppe64le)
-            echo 'ppe64le';;
-        s390x)
-            echo 's390x';;
+        i386|i486|i586|i686|x86)
+            echo 'i386';;
         *)
             echo "Error: unsupported architecture ${arch}" 1>&2
             exit 2
@@ -26,36 +31,173 @@ get_arch_repo_name() {
     esac
 }
 
+#
+# Provide platform arch for container param input
+#
+get_platform_arch() {
+    local -r arch="${1}"
+    case "${arch}" in
+        386|amd64|arm64|arm64/v8|ppc64le|s390x)
+            echo "${arch}";;
+        x86_64)
+            echo 'amd64';;
+        aarch64)
+            echo 'arm64/v8';;
+        i386|i486|i586|i686|x86)
+            echo '386';;
+        *)
+            echo "Error: unsupported architecture ${arch}" 1>&2
+            exit 2
+            ;;
+    esac
+}
+
+#
+# get build arch
+#
+# used to populate arch list for processing single or all
+get_build_arch() {
+    local -r arch="${2}"
+    local -r version=${1}
+    case "${arch}" in
+        x86_64|aarch64|ppc64le|s390x)
+            echo "${arch}";;    
+        all)
+            case "${version}" in
+                8)
+                    echo 'x86_64 aarch64 ppc64le';;
+                9)
+                    echo 'x86_64 aarch64 ppc64le s390x';;   
+            esac 
+            ;;
+        *)
+            echo "Error: unsupported architecture ${arch}" 1>&2
+            exit 2
+            ;;
+    esac
+}
+
+#
+# get build types
+#
+# used to populate arch list for processing single or all
+get_build_types() {
+    local -r type="${1}"
+    case "${type}" in
+        default|minimal|micro|base|init)
+            echo "${type}";;    
+        all)
+            echo 'default minimal micro base init';;
+        ubi)
+            echo 'micro base init';;
+        *)
+            echo "Error: unsupported image type ${type}" 1>&2
+            exit 2
+            ;;
+    esac
+}
 
 
+#
+# Provide generalized machine arch
+#
+# used for output filenames based on $(uname -m)
+get_machine_arch() {
+    local -r arch="${1}"
+    case "${arch}" in
+        x86_64|aarch64|ppc64le|s390x)
+            echo "${arch}";;    
+        amd64)
+            echo 'x86_64';;
+        arm64/v8|arm64|arm64v8)
+            echo 'aarch64';;
+        386|i386|i486|i586|i686|x86)
+            echo 'i686';;
+        *)
+            echo "Error: unsupported architecture ${arch}" 1>&2
+            exit 2
+            ;;
+    esac
+}
+
+#
+# Checks Almalinux versiona build arch is supported
+#
+#  check_build_support_arch Version Arch
+#    ex: check_build_support_arch 8 aarch64
+#
+check_build_support_arch() {
+    local -r version="${1}"
+    local -r arch="${2}"
+    case "${version}" in
+        8)
+            case "${arch}" in
+                x86_64|aarch64|ppc64le|all)
+                    echo "supported";;     
+                *)
+                    echo "Error: unsupported architecture ${arch} for version ${version}" 1>&2
+                    exit 2
+                    ;;
+            esac
+            ;;
+        9)    
+            case "${arch}" in
+                x86_64|aarch64|ppc64le|s390x|all)
+                    echo "supported";;    
+                *)
+                    echo "Error: unsupported architecture ${arch} for version ${version}" 1>&2
+                    exit 2
+                    ;;
+            esac
+            ;;
+        *)
+            echo "Error: unsupported version ${arch}" 1>&2
+            exit 2   
+            ;;
+    esac         
+}
+
+#
+# build one container image from repo files
+#
+# build_single_image_from_repos Version Arch Type buildTag
+#
+build_single_image_from_repos(){
+    local -r al_version="${1}"
+    local -r arch_platform=$(get_platform_arch "${2}")
+    local -r type="${3}"
+    local -r tag="${4}"
+    local -r build_arg="--squash"
+    docker build "$build_arg" "--platform=linux/$arch_platform" -t "${tag}" -f "dockerfiles/al${al_version}/Dockerfile.${type}" .
+}
 
 gen_rootfs() {
     local -r image="${1}"
-    local -r TNAME="${2}"
+    local -r tname="${2}"
 
-    TCNT=$(docker inspect $image | jq '.[] | .RootFS.Layers | length')
+    tcnt=$(docker inspect $image | jq '.[] | .RootFS.Layers | length')
     
-    echo "Found $TCNT layer(s) in image '$image'."
-    if [ $TCNT -ne 1 ]; then
+    echo "Found $tcnt layer(s) in image '$image'."
+    if [ $tcnt -ne 1 ]; then
         echo "Only single layer image is supported at this time. Use '--squash' option to create single layer image."
         exit
     fi
     echo "Setting up temp work dir ..."
-    mkdir -p wsl-temp && cd wsl-temp
+    mkdir -p rootfs-tmp && cd rootfs-tmp
     echo "Saving docker/container image ..."
-    docker save $image -o wsltemp.tar
-    TWSL=$(tar -tf wsltemp.tar | grep layer)
-    TCNT=$(echo $TWSL | tr ' ' '\n' | grep layer | wc -l | xargs)
-    echo "Found $TCNT layer(s) in image '$image'."
-    if [ $TCNT -eq 1 ]; then
-        echo "Extracting rootfs $TWSL ..."
-        tar -xf wsltemp.tar $TWSL
-        mv $TWSL $TNAME.tar
+    docker save $image -o rootfstmp.tar
+    trepo=$(tar -tf rootfstmp.tar | grep layer)
+    tcnt=$(echo $trepo | tr ' ' '\n' | grep layer | wc -l | xargs)
+    echo "Found $tcnt layer(s) in image '$image'."
+    if [ $tcnt -eq 1 ]; then
+        echo "Extracting rootfs $trepo ..."
+        tar -xf rootfstmp.tar $trepo
+        mv $trepo $tname.tar
         echo "Compressing rootfs ..."
-        xz $TNAME.tar
-        mv $TNAME* ../
+        xz $tname.tar
+        mv $tname* ../
         cd ..
-        F1=$(ls | grep $2)
+        F1=$(ls | grep $tname)
         TMSG="Task complete. Output rootfs located at $PWD/$F1"
     else
         echo "Only single layer image is supported at this time. Use '--squash' option to create single layer image."
@@ -63,14 +205,15 @@ gen_rootfs() {
         TMSG="Error Exit, task complete."
     fi
     echo "Perform cleanup ..."
-    rm -rf wsl-temp
+    rm -rf rootfs-tmp
     echo $TMSG
 }
 
 build_docker_file() {
 
-    repo_prefix="{1:'quay.io/almalinuxautobot'}"
+    repo_prefix="${1:'quay.io/almalinuxautobot'}"
     repo_sep=':'
+    tag_suffix="${2:$(date +%Y%m%d)}"
     # for type in micro minimal base init; 
     for type in micro; 
     do
@@ -123,3 +266,59 @@ do
 
 done
 }
+
+build_image_from_repos () {
+    # local -r version="${1}"
+    # local -r types=$(get_registry_arch ${1})
+
+    # 8 or 9
+    local -r input_version=${1}
+    # input arch env, 
+    local -r input_arch=${2}
+    # input type env
+    local -r input_type=${3}
+    local major_version=${input_version}
+    local arch_list=$(get_build_arch ${input_version} ${input_arch})
+    local type_list=$(get_build_types ${input_type})
+
+    echo "Input version " ${input_version}
+    echo "Input Arch " ${input_arch}
+    echo "Input type " ${input_type}
+    echo "Computed arch list: "${arch_list}
+    echo "Computed type list: "${type_list}
+
+    status=$(check_build_support_arch ${1} ${2})
+
+    echo "Validating input values ... ${status}" 
+    repo_prefix="srbala"
+    repo_sep=":"
+    tag_date=$(date +%Y%m%d)
+    if [ $status == 'supported' ];  then
+    echo "Ready for processing ..."
+        for arch in ${arch_list};
+        do
+            for type in ${type_list};
+            do
+                #build_tag='almalinux/'$arch$repo_sep'8-'$type'-20220608';
+                build_tag=$repo_prefix'/'$(get_registry_arch ${arch})$repo_sep${input_version}
+                if [ "$type" == "default" ]; then
+                    build_tag=$build_tag'-'$tag_date
+                else   
+                    build_tag=$build_tag'-'$type'-'$tag_date
+                fi
+                # build_single_image_from_repos 9 "${1}" minimal "t-minimal-$(get_registry_arch ${1})"
+                echo "build_single_image_from_repos ${input_version} ${arch} $type $build_tag"
+                build_single_image_from_repos ${input_version} ${arch} $type $build_tag
+                file_prefix='almalinux-'${input_version}'-'$(get_machine_arch ${arch})'-'$type
+                gen_rootfs $build_tag $file_prefix
+                #docker push $build_tag
+
+            done
+        done
+    else
+    echo "Input value error"
+    fi
+}
+
+
+build_image_from_repos ${1} ${2} ${3}
