incremental udpate

diff --git a/image_build b/image_build
--- a/image_build
+++ b/image_build
@@ -8,6 +8,33 @@ TYPE=''
 
 OPTIND=1
 
+#
+# Return OS Release name like `AlmaLinux release 9.0 (Emerald Puma)` for audit log
+#
+get_os_release() {
+    local -r image=${1}
+    # issue docker pull, redirect messages to null
+    docker pull ${image} > /dev/null
+    local rel=$(docker run --rm -it ${image} cat /etc/system-release)
+    echo $rel
+}
+
+get_image_hash() {
+    local -r image=${1}
+    # issue docker pull, redirect messages to null
+    docker pull ${image} > /dev/null
+    local hash=$(docker inspect ${image} | jq '.[] .Id' | tr -d '"')
+    echo $hash
+}
+
+get_os_release_version() {
+    local -r image=${1}
+    # issue docker pull, redirect messages to null
+    docker pull ${image} > /dev/null
+    local rel=$(docker run --rm ${image} awk '{ print $3 }' /etc/system-release )
+    # local rel=$(docker run --rm ${image} awk -F= '$1=="VERSION_ID" { print $2 ;}' /etc/os-release | tr -d '"')
+    echo $rel
+}
 
 #
 # Provide arch names for registory path
@@ -160,17 +187,39 @@ check_build_support_arch() {
 #
 # build one container image from repo files
 #
-# build_single_image_from_repos Version Arch Type buildTag
+# build_single_image_using_repos Version Arch Type builtag_suffix
 #
-build_single_image_from_repos(){
+build_single_image_using_repos(){
     local -r al_version="${1}"
     local -r arch_platform=$(get_platform_arch "${2}")
     local -r type="${3}"
     local -r tag="${4}"
     local -r build_arg="--squash"
+    echo "Building for arch: $arch_platform"
     docker build "$build_arg" "--platform=linux/$arch_platform" -t "${tag}" -f "dockerfiles/al${al_version}/Dockerfile.${type}" .
 }
 
+#
+# build one container image from rootfs files, usually right before publishing the images
+#
+# build_single_image_using_rootfs Version Arch Type builtag_suffix
+#
+build_single_image_using_rootfs(){
+    local -r al_version="${1}"
+    local -r arch_platform=$(get_platform_arch "${2}")
+    local -r type="${3}"
+    local -r tag="${4}"
+    local -r arch_machine=$(get_machine_arch "${2}")
+
+    docker build "--platform=linux/$arch_platform" -t "${tag}" -f "Dockerfile-${arch_machine}-${type}" .
+    docker push "${tag}"
+}
+
+#
+# Extract rootfs file from a container image (image_tag), creates rootfs `rootfs_outfile_prefix.tar.xz`
+#
+# gen_rootfs image_tag  rootfs_outfile_prefix
+#
 gen_rootfs() {
     local -r image="${1}"
     local -r tname="${2}"
@@ -209,116 +258,158 @@ gen_rootfs() {
     echo $TMSG
 }
 
-build_docker_file() {
+#
+# pull_docker_official  "9" "0" "minimal" "20220623"
+#
+# pull_docker_official for "default" or "minimal", do-not rebuild for publish
+#
+pull_docker_official() {
+    local -r al_version="${1}"
+    local -r rel_version="${2}"
+    local -r types="${3}"
+    local -r repo_prefix="${4}"
+    local -r date_suffix="${5}"
 
-    repo_prefix="${1:'quay.io/almalinuxautobot'}"
-    repo_sep=':'
-    tag_suffix="${2:$(date +%Y%m%d)}"
-    # for type in micro minimal base init; 
-    for type in micro; 
-    do
-        for arch in amd64 arm64/v8 ppc64le;
+    local tag="$al_version.$rel_version"
+    if [[ $type == "minimal" ]]; then
+        tag="$tag-$type"
+    fi
+    tag="$tag-$date_suffix"
+    docker pull docker.io/amd64/almalinux:$tag
+    docker tag docker.io/amd64/almalinux:$tag "$repo_prefix/amd64:$tag"
+    docker push "$repo_prefix/amd64:$tag"
+    docker pull docker.io/arm64v8/almalinux:$tag
+    docker tag docker.io/arm64v8/almalinux:$tag "$repo_prefix/arm64v8:$tag"
+    docker push "$repo_prefix/arm64v8:$tag"
+    docker pull docker.io/ppc64le/almalinux:$tag
+    docker tag docker.io/ppc64le/almalinux:$tag "$repo_prefix/ppc64le:$tag"
+    docker push "$repo_prefix/ppc64le:$tag"
+    if [[ $al_version == "9" ]]; then
+        docker pull docker.io/s390x/almalinux:$tag
+        docker tag docker.io/s390x/almalinux:$tag "$repo_prefix/s390x:$tag"
+        docker push "$repo_prefix/s390x:$tag"
+    fi
 
+}
+
+# build_ubi_manifest 9 0 micro 20220623
+build_ubi_manifest() {
+    local -r al_version="${1}"
+    local -r rel_version="${2}"
+    local -r types="${3}"
+    local -r repo_prefix="${4}"
+    local -r date_suffix="${5}"
+    local -r tags="latest ${1} ${1}.${2} ${1}.${2}-${5}"
+    
+    for type in $types; 
+    do 
+        if [[ $repo_prefix == *"docker"* &&  $type == "default" ]]; then
+            echo "No place holder for default in user space"
+        else
+        if [[ $type == "default" || $type == "minimal" ]]; then
+            pull_docker_official ${1} ${2} ${3} ${4} ${5} 
+        else
+            build_images ${1} ${2} "all" $type ${4} ${5} "rootfs"
+        fi
+        for tag in $tags
         do
-            march=$arch;
-            if [[ $arch == 'arm64/v8' ]]; then
-                march='aarch64';
+            local part1="$repo_prefix"
+            local part2=""
+            local stype="-"
+            if [[ $type == "default" ]]; then
+                part1="$part1/almalinux"
+                stype=""
+            else
+                part1="$part1/$al_version-$type"
+                stype="$stype$type"
+            fi
+            part1="$part1:$tag"
+            local tag_suffix="$al_version.$rel_version$stype-$date_suffix"
+            part2="$part2 --amend $repo_prefix/amd64:$tag_suffix"
+            part2="$part2 --amend $repo_prefix/arm64v8:$tag_suffix" 
+            part2="$part2 --amend $repo_prefix/ppc64le:$tag_suffix"
+            if [ "${al_version}" == '9' ]; then
+                part2="$part2 --amend $repo_prefix/s390x:$tag_suffix"
             fi    
-            if [[ $arch == 'amd64' ]]; then
-                march='x86_64';
-            fi   
-            build_tag=$repo_prefix$repo_sep'8-'$type'-20220608-'$march;
-            docker build --squash --platform=linux/$arch -t $build_tag -f Dockerfile.$type . 
-            docker push $build_tag
-        done
+            docker manifest create $part1 $part2
+            docker manifest push $part1
+        done   
+        fi
     done
 }
 
-build_manifest() {
-    repo_prefix="${1:srbala/}"
-    types="micro minimal base init"
-    tags="latest 8 8.6 8.6-20220512"
-    dtag="20220512"
-    ver='8'
-for type in $types; 
-do 
-    if [ "${ver}" == '8' ]; then
-        for tag in $tags
-        do
-            docker manifest create --amend $repo_prefix/$ver-$type:$tag \
-                $repo_prefix/amd64:$ver-$type-$dtag \
-                $repo_prefix/arm64v8:$ver-$type-$dtag \
-                $repo_prefix/ppc64le:$ver-$type-$dtag;
-            docker manifest push $repo_prefix/$ver-$type:$tag
-        done
-    fi    
-    if [ "${ver}" == '9' ]; then
-        for tag in $tags
-        do
-            docker manifest create --amend $repo_prefix/$ver-$type:$tag \
-                $repo_prefix/amd64:$ver-$type-$dtag \
-                $repo_prefix/arm64v8:$ver-$type-$dtag \
-                $repo_prefix/ppc64le:$ver-$type-$dtag \
-                $repo_prefix/s390x:$ver-$type-$dtag ;
-            docker manifest push $repo_prefix/$ver-$type:$tag
-        done
-    fi    
-
-done
-}
-
-build_image_from_repos () {
+build_images () {
     # local -r version="${1}"
     # local -r types=$(get_registry_arch ${1})
 
     # 8 or 9
-    local -r input_version=${1}
+    local -r al_version=${1}
+    local -r rel_version=${2}
     # input arch env, 
-    local -r input_arch=${2}
+    local -r input_arch=${3}
     # input type env
-    local -r input_type=${3}
-    local major_version=${input_version}
-    local arch_list=$(get_build_arch ${input_version} ${input_arch})
+    local -r input_type=${4}
+    # repo_prefix="srbala"
+    local -r repo_prefix=${5}
+    repo_sep=":"
+    # tag_date=$(date +%Y%m%d)
+    local -r tag_date=${6}
+    local -r from=${7}
+    local arch_list=$(get_build_arch ${al_version} ${input_arch})
     local type_list=$(get_build_types ${input_type})
 
-    echo "Input version " ${input_version}
-    echo "Input Arch " ${input_arch}
-    echo "Input type " ${input_type}
-    echo "Computed arch list: "${arch_list}
-    echo "Computed type list: "${type_list}
+    echo "Input version     : ${al_version}.${rel_version}" 
+    echo "Input Arch        : ${input_arch}" 
+    echo "Input type        : ${input_type}" 
+    echo "Computed arch list: ${arch_list}" 
+    echo "Computed type list: ${type_list}" 
 
-    status=$(check_build_support_arch ${1} ${2})
+    if [[ -z "$type_list" ]]; then
+        echo "Validating input type failed ... ${input_type}" 
+        exit 2
+    fi
+
+    status=$(check_build_support_arch ${1} ${3})
 
     echo "Validating input values ... ${status}" 
-    repo_prefix="srbala"
-    repo_sep=":"
-    tag_date=$(date +%Y%m%d)
-    if [ $status == 'supported' ];  then
+
+    if [[ $status == 'supported' && ! -z "$type_list" ]];  then
     echo "Ready for processing ..."
         for arch in ${arch_list};
         do
             for type in ${type_list};
             do
                 #build_tag='almalinux/'$arch$repo_sep'8-'$type'-20220608';
-                build_tag=$repo_prefix'/'$(get_registry_arch ${arch})$repo_sep${input_version}
+                build_tag=$repo_prefix'/'$(get_registry_arch ${arch})$repo_sep${al_version}.${rel_version}
                 if [ "$type" == "default" ]; then
                     build_tag=$build_tag'-'$tag_date
                 else   
                     build_tag=$build_tag'-'$type'-'$tag_date
                 fi
-                # build_single_image_from_repos 9 "${1}" minimal "t-minimal-$(get_registry_arch ${1})"
-                echo "build_single_image_from_repos ${input_version} ${arch} $type $build_tag"
-                build_single_image_from_repos ${input_version} ${arch} $type $build_tag
-                file_prefix='almalinux-'${input_version}'-'$(get_machine_arch ${arch})'-'$type
-                gen_rootfs $build_tag $file_prefix
-                #docker push $build_tag
-
+                if [[ "$from" == "repos" ]]; then
+                    # build_single_image_using_repos 9 "${1}" minimal "t-minimal-$(get_registry_arch ${1})"
+                    echo "build_single_image_using_repos ${al_version} ${arch} $type $build_tag"
+                    build_single_image_using_repos ${al_version} ${arch} $type $build_tag
+                    file_prefix='almalinux-'${al_version}'-'$(get_machine_arch ${arch})'-'$type
+                    gen_rootfs $build_tag $file_prefix
+                    #docker push $build_tag
+                fi
+                if [[ "$from" == "rootfs" ]]; then
+                    build_single_image_using_rootfs  ${al_version} ${arch} $type $build_tag 
+                fi
             done
         done
     else
-    echo "Input value error"
+        echo "Input value error"
     fi
 }
+# build_image_from_repos ${1} ${2} ${3} "srbala"  $(date +%Y%m%d)
+# get_image_hash ${1}
+# get_os_release_version ${1}
+# pull_docker_official 8 6 20220512
+# build_images 9 0 "all" "micro" "srbala"  $(date +%Y%m%d) "rootfs"
+# build_images 9 0 "all" "micro" "srbala1"  $(date +%Y%m%d) "repos"
 
+# build_ubi_manifest "9" "0" "micro" "quay.io/almalinuxautobot" "20220527"
 
-build_image_from_repos ${1} ${2} ${3}
+# build_images "9" "0" "aarch64" "base" "srbala1"  20220527 "repos"
